/**
 * SNS instrument presets with detector geometry: the catalog (instrumentCatalog.ts)
 * plus panels and L1 from the Mantid instrument definitions (src/data/instruments.json,
 * generated by scripts/data/idf.ts; validated on TOPAZ_3007 in
 * src/core/instrument/detectors.test.ts). Loaded with the simulation pages, so the
 * geometry downloads only when one is opened.
 */
import geometry from "../../data/instruments.json";
import type { DetectorPanel } from "../instrument/detectors.ts";
import { SNS_CATALOG } from "./instrumentCatalog.ts";
import type { InstrumentPreset } from "./instruments.ts";

const byId = (id: string) => {
  const ins = geometry.instruments.find((i) => i.id === id);
  if (!ins) throw new Error(`No detector geometry for ${id}`);
  return ins;
};

export const SNS_INSTRUMENTS: readonly InstrumentPreset[] = SNS_CATALOG.map(({ geometry: id, ...entry }) => {
  const ins = byId(id);
  return {
    ...entry,
    l1: ins.l1,
    detectors: ins.panels as unknown as DetectorPanel[],
    source: `${entry.source} Detectors: Mantid ${ins.idf.url.split("/").pop()} (valid from ${ins.idf.validFrom.slice(0, 10)}).`,
  };
});
