/**
 * Experimental instrument presets with detector geometry, loaded only when
 * EXPERIMENTAL is on (src/app/experimental.ts).
 *
 * Detector panels come from Mantid instrument definitions (src/data/instruments.json,
 * generated by scripts/data/idf.ts; validated on TOPAZ_3007 in
 * src/core/instrument/detectors.test.ts). Goniometers and bands:
 *  - TOPAZ: see instruments.ts (cryogenic ω; ambient ω, φ with χ = 135°), 0.4–3.5 Å.
 *  - CORELLI: BL9:Mot:Sample:Axis1–3, each (0,1,0,+1) (neutrons/garnet-tools
 *    src/garnet/config/instruments.py @ 4eb3206); 0.6–2.5 Å (same file; within ORNL's
 *    10–200 meV incident-energy range).
 *  - NOMAD (0.1–3 Å, ORNL instrument page) and POWGEN are powder diffractometers with no
 *    sample goniometer; a generic vertical rotation stands in. POWGEN's band depends on the
 *    choppers: the default is one 60 Hz frame (≈ 3956/(60·63) ≈ 1.05 Å wide for its ~63 m
 *    flight path) centred on 1.066 Å; adjust it to the chopper setting.
 */
import geometry from "../../data/instruments.json";
import type { DetectorPanel } from "../instrument/detectors.ts";
import { CHI, OMEGA, PHI, type InstrumentPreset } from "./instruments.ts";

const panels = (id: string): DetectorPanel[] => {
  const ins = geometry.instruments.find((i) => i.id === id);
  if (!ins) throw new Error(`No detector geometry for ${id}`);
  return ins.panels as unknown as DetectorPanel[];
};
const l1 = (id: string) => geometry.instruments.find((i) => i.id === id)!.l1;
const idfNote = (id: string) => {
  const ins = geometry.instruments.find((i) => i.id === id)!;
  return `Detectors: Mantid ${ins.idf.url.split("/").pop()} (valid from ${ins.idf.validFrom.slice(0, 10)}).`;
};
const GENERIC_OMEGA = { ...OMEGA, name: "ω", min: 0, max: 360 };

export const EXPERIMENTAL_INSTRUMENTS: readonly InstrumentPreset[] = [
  {
    id: "topaz-cryo",
    label: "TOPAZ · cryogenic goniometer (ω)",
    goniometer: { id: "topaz-cryo", label: "TOPAZ cryogenic", axes: [{ ...OMEGA, min: 0, max: 360, log: "BL12:Mot:Gonioc:Omega" }], note: "ω about the vertical +y axis, counter-clockwise (χ = φ = 0)." },
    lambdaMin: 0.4,
    lambdaMax: 3.5,
    l1: l1("TOPAZ"),
    detectors: panels("TOPAZ"),
    source: `garnet-tools and NeuXtalViz TOPAZ configs; ORNL TOPAZ specification (0.4–3.5 Å). ${idfNote("TOPAZ")}`,
    experimental: true,
  },
  {
    id: "topaz-ambient",
    label: "TOPAZ · ambient goniometer (ω, φ; χ = 135°)",
    goniometer: {
      id: "topaz-ambient",
      label: "TOPAZ ambient",
      axes: [
        { ...OMEGA, min: 0, max: 360, log: "BL12:Mot:omega" },
        { ...CHI, fixed: 135, log: "BL12:Mot:chi" },
        { ...PHI, min: 0, max: 360, log: "BL12:Mot:phi" },
      ],
      note: "Mantid Universal axes with χ fixed at 135°.",
    },
    lambdaMin: 0.4,
    lambdaMax: 3.5,
    l1: l1("TOPAZ"),
    detectors: panels("TOPAZ"),
    source: `garnet-tools and NeuXtalViz TOPAZ configs; ORNL TOPAZ page (χ fixed at 135°). ${idfNote("TOPAZ")}`,
    experimental: true,
  },
  {
    id: "corelli",
    label: "CORELLI · sample rotation (Axis1–3)",
    goniometer: {
      id: "corelli",
      label: "CORELLI",
      axes: [
        { ...OMEGA, name: "Axis1", min: 0, max: 360, log: "BL9:Mot:Sample:Axis1" },
        { ...OMEGA, name: "Axis2", min: -180, max: 180, log: "BL9:Mot:Sample:Axis2" },
        { ...OMEGA, name: "Axis3", min: -180, max: 180, log: "BL9:Mot:Sample:Axis3" },
      ],
      note: "Three stacked rotations, all about the vertical +y axis, counter-clockwise.",
    },
    lambdaMin: 0.6,
    lambdaMax: 2.5,
    l1: l1("CORELLI"),
    detectors: panels("CORELLI"),
    source: `garnet-tools CORELLI config (axes, 0.6–2.5 Å). ${idfNote("CORELLI")}`,
    experimental: true,
  },
  {
    id: "nomad",
    label: "NOMAD · detectors (generic ω)",
    goniometer: { id: "nomad", label: "NOMAD", axes: [GENERIC_OMEGA], note: "NOMAD has no sample goniometer; ω is a generic vertical rotation." },
    lambdaMin: 0.1,
    lambdaMax: 3.0,
    l1: l1("NOMAD"),
    detectors: panels("NOMAD"),
    source: `ORNL NOMAD page (0.1–3 Å, 19.5 m). ${idfNote("NOMAD")}`,
    experimental: true,
  },
  {
    id: "powgen",
    label: "POWGEN · detectors (generic ω)",
    goniometer: { id: "powgen", label: "POWGEN", axes: [GENERIC_OMEGA], note: "POWGEN has no sample goniometer; ω is a generic vertical rotation." },
    lambdaMin: 0.54,
    lambdaMax: 1.59,
    l1: l1("POWGEN"),
    detectors: panels("POWGEN"),
    source: `ORNL POWGEN page (60 m). Band: one 60 Hz frame around 1.066 Å; set it to your chopper setting. ${idfNote("POWGEN")}`,
    experimental: true,
  },
];
