"""Generate fixtures/pychop-resolution.json: Mantid PyChop's energy resolution for ARCS, SEQUOIA and CNCS.

PyChop (mantid scripts/pychop @ 67c2f43, GPL-3.0-or-later) is the reference for the closed-form port in
src/core/instrument/pychop.ts. Its files are pinned in data-sources/sources.json (npm run data:fetch puts them in
data-sources/cache/pychop-*); this script assembles them into a package and records getResolution (FWHM, meV)
over a grid of chopper settings, incident energies and energy transfers. A setting PyChop finds closed
(no transmission) is recorded as null.

Run:  uv run --no-project --with numpy --with scipy --with pyyaml python scripts/data/gen_pychop_reference.py
"""

import json
import math
import shutil
import sys
import tempfile
import warnings
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / "data-sources" / "cache"
FILES = {"pychop-init": "__init__.py", "pychop-instruments": "Instruments.py", "pychop-chop": "Chop.py", "pychop-mulpyrep": "MulpyRep.py", "pychop-arcs": "arcs.yaml", "pychop-sequoia": "sequoia.yaml", "pychop-cncs": "cncs.yaml"}

pkg = Path(tempfile.mkdtemp()) / "pychop"
pkg.mkdir()
for source, name in FILES.items():
    shutil.copy(CACHE / source / name, pkg / name)
sys.path.insert(0, str(pkg.parent))
warnings.simplefilter("ignore")
from pychop.Instruments import Instrument  # noqa: E402

import numpy  # noqa: E402
import scipy  # noqa: E402


def resolution(instrument, chopper, freq, ei, et):
    ins = Instrument(instrument)
    ins.setChopper(chopper, freq)
    ins.ei = ei
    v = float(ins.getResolution(et)[0])
    return v if math.isfinite(v) else None


rows = []
for instrument, packages, freqs, eis in [
    ("arcs", ["ARCS-100-1.5-AST", "ARCS-700-1.5-AST", "ARCS-700-0.5-AST"], [60, 180, 300, 600], [8, 15, 60, 150, 400, 1000]),
    ("sequoia", ["SEQ-100-2.0-AST", "SEQ-700-3.5-AST", "SEQ-1000-1.5-AST", "ARCS-700-0.5-AST"], [60, 240, 360, 600], [6, 10, 50, 120, 500, 2000]),
]:
    for package in packages:
        for f in freqs:
            for ei in eis:
                for frac in [0, 0.25, 0.5, 0.75, -0.3]:
                    rows.append({"instrument": instrument, "chopper": package, "frequency": f, "ei": ei, "transfer": frac * ei, "fwhm": resolution(instrument, package, f, ei, frac * ei)})
for mode in ["High Flux", "Intermediate", "High Resolution"]:
    for f in [60, 120, 180, 240, 300]:
        for ei in [0.5, 1.0, 3.32, 6.59, 12.0, 25.0]:
            for frac in [0, 0.5, 0.8, -0.5]:
                rows.append({"instrument": "cncs", "chopper": mode, "frequency": f, "ei": ei, "transfer": frac * ei, "fwhm": resolution("cncs", mode, [f, 60], ei, frac * ei)})

out = {
    "description": "Mantid PyChop getResolution (energy FWHM, meV) at mantid 67c2f43; CNCS with chopper 1 at 60 Hz. Generated by scripts/data/gen_pychop_reference.py.",
    "versions": {"numpy": numpy.__version__, "scipy": scipy.__version__},
    "rows": rows,
}
dest = ROOT / "fixtures" / "pychop-resolution.json"
dest.write_text(json.dumps(out, indent=1) + "\n")
print(f"wrote {dest.relative_to(ROOT)}: {len(rows)} rows, {sum(r['fwhm'] is None for r in rows)} closed")
