"""Generate fixtures/qres-garnet.json: ORNL garnet-tools' Q-resolution covariance for TOPAZ and CORELLI.

garnet-tools (neutrons/garnet-tools @ 4eb3206, BSD-3-Clause) is the reference for src/core/instrument/qResolution.ts.
Its files are pinned in data-sources/sources.json (npm run data:fetch puts them in data-sources/cache/garnet-*).
resolution.py imports Mantid at the top, so its model methods (_model_design_lab, _outer6, _vech6,
set_variance_parameters, set_variance_parameters_deg) are lifted out with `ast` and run on their own, with the
fitted DivergenceParams of config/instruments.py and the isotropic mosaic model. The calibration crystal's fitted
mosaic is set to zero (NEXPLAN takes the sample's as an input). garnet's S is on a 99.7 % containment scale; the
fixture stores the Gaussian covariance S/χ²₃(0.997) in Å⁻² (Q with 2π).

Run:  uv run --no-project --with numpy --with scipy python scripts/data/gen_qres_reference.py
"""

import ast
import json
from pathlib import Path

import numpy as np
import scipy
from scipy.stats import chi2

ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / "data-sources" / "cache"
WANTED = {"_vech6", "_outer6", "_model_design_lab", "set_variance_parameters", "set_variance_parameters_deg"}

source = (CACHE / "garnet-resolution" / "resolution.py").read_text()
methods = []
for node in ast.walk(ast.parse(source)):
    if isinstance(node, ast.ClassDef):
        found = [f for f in node.body if isinstance(f, ast.FunctionDef) and f.name in WANTED]
        if {f.name for f in found} == WANTED:
            methods = found
            break
assert methods, "garnet-tools resolution.py: model methods not found"
cls = ast.ClassDef(name="Model", bases=[], keywords=[], body=methods, decorator_list=[])
module = ast.Module(body=[cls], type_ignores=[])
namespace = {"np": np}
exec(compile(ast.fix_missing_locations(module), "garnet-resolution", "exec"), namespace)
Model = namespace["Model"]

beamlines = {}
exec((CACHE / "garnet-instruments" / "instruments.py").read_text(), {}, beamlines)
beamlines = beamlines["beamlines"]

containment = chi2.ppf(0.997, df=3)
rows = []
for name in ["TOPAZ", "CORELLI"]:
    m = Model()
    m.mosaic = "isotropic"
    params = {**beamlines[name]["DivergenceParams"], "sigma_mosaic": 0.0}
    model = m.set_variance_parameters_deg(params)
    lo, hi = beamlines[name]["Wavelength"]
    for tt in [10, 30, 60, 90, 120, 150, 170]:
        for phi in [0, 35, -70, 180]:
            for lam in np.linspace(lo, hi, 5):
                A = m._model_design_lab(np.radians(tt), np.radians(phi), lam, np.eye(3), lambda_0_gamma_i=model["lambda_0_gamma_i"], lambda_0_nu_i=model["lambda_0_nu_i"], q_i=model["q_i"])
                y = A @ model["variance_parameters"]
                S = np.array([[y[0], y[5], y[4]], [y[5], y[1], y[3]], [y[4], y[3], y[2]]]) / containment
                rows.append({"instrument": name, "twoTheta": tt, "phi": phi, "lambda": float(lam), "covariance": S.tolist()})

out = {
    "description": "garnet-tools @ 4eb3206 resolution model (isotropic mosaic, calibration mosaic set to 0): Gaussian Q covariance (1/A^2, Q = 2*pi/d), lab frame, k_f = (sin 2th cos phi, sin 2th sin phi, cos 2th). Generated by scripts/data/gen_qres_reference.py.",
    "versions": {"numpy": np.__version__, "scipy": scipy.__version__},
    "containment": containment,
    "rows": rows,
}
dest = ROOT / "fixtures" / "qres-garnet.json"
dest.write_text(json.dumps(out, indent=1) + "\n")
print(f"wrote {dest.relative_to(ROOT)}: {len(rows)} rows")
